<?php
function website_schema(array $config):array{return ['@context'=>'https://schema.org','@type'=>'WebSite','name'=>$config['site_name']??'ASMR Audio Online','url'=>rtrim($config['base_url']??'','/')];}
function organization_schema(array $config):array{$schema=['@context'=>'https://schema.org','@type'=>'Organization','name'=>$config['site_name']??'ASMR Audio Online','url'=>rtrim($config['base_url']??'','/')];if(!empty($config['site_logo']))$schema['logo']=$config['site_logo'];if(!empty($config['social_links']))$schema['sameAs']=array_values(array_filter($config['social_links'],'is_string'));return $schema;}
function breadcrumb_schema(array $items):array{$list=[];$position=1;foreach($items as $name=>$item){$list[]=['@type'=>'ListItem','position'=>$position++,'name'=>$name,'item'=>$item];}return ['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>$list];}
function article_schema(array $article,string $canonical):array{global $config;$type=in_array($article['schema_type']??'',['Article','BlogPosting'],true)?$article['schema_type']:'Article';$publisherName=$config['site_name']??'ASMR Audio Online';$description=!empty($article['meta_description'])?$article['meta_description']:($article['excerpt']??'');$s=['@context'=>'https://schema.org','@type'=>$type,'headline'=>$article['title']??'','description'=>$description,'url'=>$canonical,'mainEntityOfPage'=>['@type'=>'WebPage','@id'=>$canonical],'author'=>['@type'=>'Person','name'=>$article['author']??'ASMR Audio Online'],'publisher'=>['@type'=>'Organization','name'=>$publisherName,'url'=>rtrim($config['base_url']??'','/')]];if(!empty($config['site_logo']))$s['publisher']['logo']=['@type'=>'ImageObject','url'=>$config['site_logo']];if(!empty($article['published_at']))$s['datePublished']=date(DATE_ATOM,strtotime($article['published_at']));if(!empty($article['updated_at']))$s['dateModified']=date(DATE_ATOM,strtotime($article['updated_at']));if(!empty($article['featured_image']))$s['image']=media_url($article['featured_image']);return $s;}
function product_schema(array $product,string $canonical):array{$s=['@context'=>'https://schema.org','@type'=>'Product','name'=>$product['product_name']??'','description'=>$product['short_description']??'','url'=>$canonical];if(!empty($product['brand']))$s['brand']=['@type'=>'Brand','name'=>$product['brand']];if(!empty($product['image']))$s['image']=url($product['image']);return $s;}
function creator_schema(array $creator,string $canonical):array{$s=['@context'=>'https://schema.org','@type'=>'Person','name'=>$creator['name']??'','url'=>$canonical];if(!empty($creator['profile_image']))$s['image']=url($creator['profile_image']);if(!empty($creator['country']))$s['nationality']=$creator['country'];if(!empty($creator['youtube_url']))$s['sameAs']=[$creator['youtube_url']];return $s;}
function audio_schema(array $audio,string $canonical):array{$s=['@context'=>'https://schema.org','@type'=>'AudioObject','name'=>$audio['title']??'','description'=>$audio['description']??'','url'=>$canonical,'contentUrl'=>$audio['audio_url']??''];if(!empty($audio['duration_seconds']))$s['duration']='PT'.(int)$audio['duration_seconds'].'S';return $s;}
function render_schema(array $schema):void{echo '<script type="application/ld+json">'.json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).'</script>';}
function faq_schema(array $items):array{$entities=[];foreach($items as $item){if(!empty($item['question'])&&!empty($item['answer']))$entities[]=['@type'=>'Question','name'=>$item['question'],'acceptedAnswer'=>['@type'=>'Answer','text'=>$item['answer']]];}return ['@type'=>'FAQPage','mainEntity'=>$entities];}
function item_list_schema(array $items):array{$elements=[];$position=1;foreach($items as $item){$elements[]=['@type'=>'ListItem','position'=>$position++,'url'=>$item['url'],'name'=>$item['name']];}return ['@type'=>'ItemList','itemListElement'=>$elements];}
